name: CD
on:
  push:
    branches: [master]
    tags-ignore: ["v*"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: andrewscwei/actions/node-build@v2
      - name: Test
        run: npm test
      - name: Deploy to GitHub pages
        uses: andrewscwei/actions/gh-pages-deploy@v2
        with:
          cname: ${{ vars.CNAME }}
          deploy-path: build
  notify:
    name: Notify
    needs: [deploy]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.deploy.result == 'success' }}
          cancelled: ${{ needs.deploy.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
